Repository maple-labs/loan, pull requests merged in 2021-09, with the labels that each got.

#20 feat: Cleanup extra asset helpers
  contracts/LoanPrimitive.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#18 Feat: Basic Events
  contracts/Loan.sol
  contracts/LoanPrimitive.sol
  contracts/interfaces/ILoan.sol
  contracts/test/accounts/Lender.sol
  contracts/test/accounts/LoanUser.sol
Labels: Priority: Medium, Status: Revisions Needed

#19 Fix: Pay back remaining principal, on last payment, for under-amortized loans
  contracts/LoanPrimitive.sol
  contracts/test/Loan.t.sol
  contracts/test/LoanStories.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#21 refactor: Natspec and Variables
  contracts/Loan.sol
  contracts/LoanPrimitive.sol
  contracts/interfaces/ILoan.sol
  contracts/test/accounts/Borrower.sol
  contracts/test/accounts/Lender.sol
  contracts/test/accounts/LoanUser.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#23 feat: Lend unit tests (SC-3752)
  contracts/test/Loan.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: High, Status: Ready for Review

#24 refactor: Various Small Fixes
  contracts/LoanPrimitive.sol
Labels: Priority: Medium, Status: Ready for Review

#25 feat: Split fee and installment tests into separate contracts
  contracts/test/Loan.t.sol
Labels: Status: Ready for Review

#26 feat: Tests for post and remove collateral (SC-3756)
  .circleci/config.yml
  contracts/test/Loan.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: High, Status: Ready for Review

#27 feat: `_drawdownFunds` primitive testing (SC-3753)
  contracts/LoanPrimitive.sol
  contracts/test/Loan.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: High, Status: Ready for Review

#28 chore: Reorder functions, label sections
  contracts/Loan.sol
Labels: Priority: High, Status: Ready for Review

#32 chore: Loan Primitive Test Cleanup
  contracts/test/LoanPrimitive.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: High, Status: Ready for Review

#31 feat: Proxied MapleLoan
  config/ci.json
  config/dev.json
  config/prod.json
  contracts/LoanPrimitive.sol
  contracts/MapleLoan.sol
  contracts/MapleLoanFactory.sol
  contracts/MapleLoanInitializer.sol
  contracts/interfaces/IMapleLoan.sol
  contracts/interfaces/IMapleLoanEvents.sol
  contracts/interfaces/IMapleLoanFactory.sol
  contracts/test/MapleLoanFactory.t.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/accounts/Borrower.sol
  contracts/test/accounts/Governor.sol
  contracts/test/accounts/LoanUser.sol
Labels: Priority: High, Status: Ready for Review

#33 feat: Primitive testing for `_repossess` (SC-3805)
  contracts/LoanPrimitive.sol
  contracts/test/LoanPrimitive.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
  test.sh
Labels: Priority: High, Status: Ready for Review

#34 chore: Test `_returnFunds` and `_claimFunds`
  contracts/test/LoanPrimitive.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#37 formatting: Update param names and alignment
  contracts/LoanPrimitive.sol
  contracts/MapleLoan.sol
  contracts/MapleLoanFactory.sol
  contracts/interfaces/IMapleLoan.sol
  contracts/interfaces/IMapleLoanFactory.sol
Labels: Priority: Low, Status: Ready for Review

#39 feat: fast scaled exponent
  contracts/LoanPrimitive.sol
  contracts/test/LoanPrimitive.t.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#38 feat: Refactor to `fundLoan`
  contracts/MapleLoan.sol
  contracts/interfaces/IMapleLoan.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/accounts/LoanUser.sol
Labels: Priority: High, Status: Ready for Review

#36 feat: `_makePayments` primitive testing (SC-3754)
  contracts/LoanPrimitive.sol
  contracts/test/LoanPrimitive.t.sol
Labels: Priority: High, Status: Ready for Review

#44 feat: Edge and Fuzz Installment Tests
  contracts/test/LoanPrimitive.t.sol
Labels: Priority: Medium, Status: Ready for Review

#45 feat: Clear lender after loan repossessed
  contracts/LoanPrimitive.sol
  contracts/MapleLoan.sol
Labels: Priority: Medium, Status: Ready for Review

#46 feat: Add collateral minted test (SC-3851)
  contracts/LoanPrimitive.sol
  contracts/test/LoanPrimitive.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#49 refactor: pure `_isCollateralMaintainedWith` and cleanup
  contracts/LoanPrimitive.sol
  contracts/MapleLoan.sol
  contracts/test/LoanPrimitive.t.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#50 feat: refactor to fundLoan
  contracts/MapleLoan.sol
  contracts/interfaces/IMapleLoan.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/accounts/LoanUser.sol
Labels: Status: Work In Progress
