Repository maple-labs/loan, pull requests merged in 2021-12, with the labels that each got.

#100 fix: `returnFunds` from `public` to `external` (C4 #6)
  contracts/MapleLoan.sol
Labels: Priority: Medium, Status: Ready for Review

#101 chore: strict solc version (c4 #23)
  contracts/MapleLoan.sol
  contracts/MapleLoanFactory.sol
  contracts/MapleLoanInitializer.sol
  contracts/MapleLoanInternals.sol
  contracts/Refinancer.sol
  contracts/interfaces/IMapleLoan.sol
  contracts/interfaces/IMapleLoanEvents.sol
  contracts/interfaces/IMapleLoanFactory.sol
  contracts/interfaces/IOwnable.sol
  contracts/interfaces/IRefinancer.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/MapleLoan.t.sol
  contracts/test/MapleLoanFactory.t.sol
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/Payments.t.sol
  contracts/test/Refinancer.t.sol
  contracts/test/accounts/Borrower.sol
  contracts/test/accounts/Lender.sol
  contracts/test/accounts/LoanUser.sol
  contracts/test/harnesses/MapleLoanInternalsHarness.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#102 fix: If statement gas optimization (C4 #65)
  contracts/MapleLoanInternals.sol
Labels: Priority: Medium, Status: Ready for Review

#103 fix: MapleLoan initialize validation (C4 #31)
  contracts/MapleLoanInternals.sol
Labels: Priority: Medium, Status: Ready for Review

#104 fix: `getEarlyPaymentBreakdown` SLOAD optimization (c4 #29)
  contracts/MapleLoanInternals.sol
Labels: Priority: Medium, Status: Ready for Review

#105 fix: `_fundLoan` SLOAD savings (c4 #21)
  contracts/MapleLoanInternals.sol
Labels: Priority: Medium, Status: Ready for Review

#107 fix: more gas optimizations
  contracts/MapleLoan.sol
  contracts/MapleLoanInternals.sol
Labels: Priority: Medium, Status: Ready for Review

#108 fix: Anyone can `closeLoan` using `drawableFunds` (C4 #46)
  contracts/MapleLoan.sol
  contracts/test/MapleLoan.t.sol
Labels: Priority: Medium, Status: Ready for Review

#109 fix: Anyone can `makePayment` using `drawableFunds` (c4 #56)
  contracts/MapleLoan.sol
  contracts/test/MapleLoan.t.sol
Labels: Priority: Medium, Status: Ready for Review

#110 fix: `fundLoan` high fee attack (c4 #47)
  contracts/MapleLoanInternals.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/MapleLoan.t.sol
  contracts/test/MapleLoanFactory.t.sol
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/Payments.t.sol
  contracts/test/Refinancer.t.sol
  contracts/test/harnesses/MapleLoanInternalsHarness.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#111 fix: `test_fundLoan_pushPattern` fix
  contracts/test/MapleLoan.t.sol
Labels: Priority: Medium, Status: Ready for Review

#114 feat: Changed late rate accrual to daily basis (SC-4343)
  contracts/MapleLoanInternals.sol
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/Payments.t.sol
Labels: Status: Ready for Review

#116 fix: Update `CREATE2` output in test
  contracts/test/MapleLoanFactory.t.sol
Labels: Priority: High, Status: Ready for Review

#119 feat: MapleLoanInternals `initialize()` tests
  contracts/MapleLoanInternals.sol
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/harnesses/MapleLoanInternalsHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#120 test: Add `fundLoan` tests (SC-4371)
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#118 feat: `getUnaccountedAmount` and `proposeNewTerms` tests
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/harnesses/MapleLoanInternalsHarness.sol
Labels: Priority: High, Status: Ready for Review

#121 test: Add missing unit tests for acceptNewTerms (SC-4372)
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/harnesses/MapleLoanInternalsHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#127 test: Add `drawdownFunds` transfer failure test (SC-4385)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Medium, Status: Approved

#125 test: Add `claimFunds` test for transfer failure (SC-4387)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Medium, Status: Approved

#126 test: Add _getEarlyPaymentBreakdown() test (SC-4381)
  contracts/test/MapleLoanInternals.t.sol
  contracts/test/harnesses/MapleLoanInternalsHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#128 refactor: fix getPaymentBreakdown naming
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Low, Status: Ready for Review

#124 test: Add `removeCollateral` tests (SC-4380)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Medium, Status: Ready for Review

#131 feat: Added failed transfer tests for repossess (SC-4386)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: High, Status: Ready for Review

#132 test: makePayment_overPay (SC-4388)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: High, Status: Ready for Review

#133 test: makePayment_lastPaymentClearsLoan (SC-4388)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Medium, Status: Ready for Review

#129 feat: `isCollateralMaintained` tests (SC-4383)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Medium, Status: Ready for Review

#130 test: makePayment_insufficientAmount (SC-4388)
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Medium, Status: Ready for Review

#134 test: Add `getNextPaymentBreakdown` test
  contracts/test/MapleLoanInternals.t.sol
Labels: Priority: Medium, Status: Ready for Review
