Repository maple-labs/loan, pull requests merged in 2021-10, with the labels that each got.

#52 feat: Add payments tests against CSV values (SC-3899 + SC-3900 + SC-3901)
  config/ci.json
  config/dev.json
  contracts/LoanPrimitive.sol
  contracts/test/LoanPrimitive.t.sol
  contracts/test/MapleLoanFactory.t.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/Payments.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: High, Status: Ready for Review

#53 feat: Add Refinance for static terms + tests (SC-3905)
  config/ci.json
  config/dev.json
  contracts/MapleLoan.sol
  contracts/Refinancer.sol
  contracts/interfaces/IMapleLoan.sol
  contracts/interfaces/IMapleLoanEvents.sol
  contracts/test/MapleLoanStories.t.sol
  contracts/test/Refinancer.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Low, Status: Ready for Review

#57 chore: function reorder
  contracts/LoanPrimitive.sol
  contracts/test/harnesses/LoanPrimitiveHarness.sol
Labels: Priority: Medium, Status: Ready for Review

#60 chore: Lender Cleanup
  contracts/test/MapleLoanStories.t.sol
  contracts/test/Payments.t.sol
  contracts/test/Refinancer.t.sol
  contracts/test/accounts/Borrower.sol
  contracts/test/accounts/Lender.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#64 feat: Early repayments payments test, update early payments calculation (SC-3903)
  contracts/MapleLoanInternals.sol
  contracts/test/Payments.t.sol
Labels: Priority: High, Status: Ready for Review
