Repository maple-labs/loan, pull requests merged in 2022-03, with the labels that each got.

#145 fix: Fix `EstablishmentFeesSet` event being emitted prematurely (SC-4917)
  contracts/MapleLoanInitializer.sol
Labels: Priority: Low, Status: Ready for Review

#146 fix: Update fuzz tests to ensure `deadline` is not accidentally elapsed (SC-4919)
  contracts/MapleLoan.sol
  contracts/interfaces/IMapleLoan.sol
  contracts/test/Refinancer.t.sol
Labels: Priority: Low, Status: Ready for Review

#150 ci: Update submodules install step
  .github/workflows/pull-request.yml
  .github/workflows/push-to-main.yml
Labels: Priority: High, Status: Ready for Review

#152 fix: C4 - Fix typos (SC-5352)
  contracts/interfaces/IOwnable.sol
Labels: Status: Ready for Review

#154 fix: C4 - Check data length (SC-5346)
  contracts/MapleLoanInternals.sol
Labels: Status: Ready for Review

#153 fix: Fix `decreasePrincipal` bug (SC-5269)
  contracts/Refinancer.sol
  contracts/test/Refinancer.t.sol
Labels: Priority: High, Status: Ready for Review

#157 fix: Refinance fuzz test
  contracts/test/Refinancer.t.sol
Labels: Status: Ready for Review

#156 fix: C4 - Cache array length (SC-5377)
  contracts/MapleLoanInternals.sol
Labels: Status: Ready for Review
